version: '1'

services:
  db:
    image: mysql:8.0
    container_name: django_for_production_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'UTC'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-allowed-packet=512M
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT}:3306
